run_name: "LS_augerat_B"

exit_on_invalid: true

dataset:
  cls: cvrp.dataset.xml.XmlDirDataset
  kwargs:
    dir: data/augerat-1995-B

solver:
  cls: cvrp.solver.ls.solve.LocalSearchSolver
  kwargs:
    max_iters: 300
    early_stop: 10
    timeout_s: 900
    max_neighbor_size: 2000
    tabu_size: 300
    operators:
      - relocate
      - 2-opt*
      - or-opt
