run_name: "LS_augerat_A"

exit_on_invalid: true

dataset:
  cls: cvrp.dataset.xml.XmlDirDataset
  kwargs:
    dir: data/augerat-1995-A

solver:
  cls: cvrp.solver.ls.LocalSearchSolver
  kwargs:
    max_iters: 100
