run_name: "LS_cmt"

exit_on_invalid: true

dataset:
  cls: cvrp.dataset.xml.XmlDirDataset
  kwargs:
    dir: data/christofides-1979

solver:
  cls: cvrp.solver.ls.solve.LocalSearchSolver
  kwargs:
    restarts: 0
    short_term_max_iters: 300
    short_term_early_stop: 10
    divers_max_iters: 300
    divers_early_stop: 20
    intens_max_iters: 300
    intens_early_stop: 5
    max_neighbor_size: 3000
    elite_set_size: 10
    short_term_tabu_size: 300
    divers_tabu_size: 400
    intens_tabu_size: 200
    operators:
      - relocate
      - 2-opt*
      - or-opt
