run_name: "example"

exit_on_invalid: true

dataset:
  cls: cvrp.dataset.xml.XmlDataset
  kwargs:
    paths:
      - data/christofides-1979/CMT01.xml

solver:
  cls: cvrp.solver.cw.ClarkeWrightSolver
  kwargs: {}
